kind: Pod
apiVersion: v1
metadata:
  name: nginx-server
  labels:
    name: frontend
    project: expense
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    